import type { Connector, Inquiry } from './types'

export const initialInquiries: Inquiry[] = [
  {
    id: 'CASE-104',
    customerId: 'CUS-A',
    customerLanguage: 'French',
    channel: 'WhatsApp',
    receivedAt: '09:14',
    message: 'Can I collect my car this afternoon?',
    jobId: 'JOB-1',
    vehicle: 'ABC-123 · Service visit',
    classification: 'Collection status',
    confidence: 96,
    status: 'needs_review',
    justification: 'The workshop reports that work is finished, but the final quality check is still pending. The CRM reports the vehicle as ready, creating a conflict that prevents a safe collection promise.',
    rules: ['Conflicting states require review', 'Only a service adviser can promise collection'],
    evidence: [
      { source: 'Workshop', value: 'Work finished', observedAt: '09:00', tone: 'positive' },
      { source: 'Quality control', value: 'Check pending', observedAt: '09:00', tone: 'warning' },
      { source: 'CRM', value: 'Ready for collection', observedAt: '09:00', tone: 'warning' },
    ],
    proposedResponse: 'The workshop has completed the work, but the final quality check is still pending. I cannot confirm collection yet. A service adviser will review this and contact you.',
  },
  {
    id: 'CASE-105',
    customerId: 'CUS-A',
    customerLanguage: 'French',
    channel: 'Phone note',
    receivedAt: '09:21',
    message: 'I asked about collecting the same car. Please call me.',
    jobId: 'JOB-1',
    vehicle: 'ABC-123 · Service visit',
    classification: 'Repeated enquiry',
    confidence: 91,
    status: 'needs_review',
    justification: 'This message concerns the same vehicle and unresolved collection request as CASE-104. It should be grouped with the open case so the customer does not have to repeat the issue.',
    rules: ['Use customer IDs, never guessed identity matches', 'Group related enquiries'],
    evidence: [
      { source: 'Conversation history', value: 'Open case CASE-104', observedAt: '09:14' },
      { source: 'Contact permission', value: 'Service updates only', observedAt: 'Customer record', tone: 'warning' },
    ],
    proposedResponse: 'I found your earlier request about the same vehicle. Collection is not yet confirmed because the quality check is pending. A service adviser is reviewing the case.',
  },
  {
    id: 'CASE-106',
    customerId: 'CUS-B',
    customerLanguage: 'English',
    channel: 'Gmail',
    receivedAt: '09:32',
    message: 'I need to change my service booking.',
    jobId: 'JOB-2',
    vehicle: 'XYZ-908 · Scheduled service',
    classification: 'Booking change',
    confidence: 98,
    status: 'ready',
    justification: 'A confirmed booking exists for Day 2 at 10:00. The customer permits callbacks only, so the safe next step is to prepare a callback rather than alter the booking automatically.',
    rules: ['Respect customer contact permission', 'Do not confirm simulated booking changes'],
    evidence: [
      { source: 'Booking system', value: 'Day 2, 10:00', observedAt: '09:10', tone: 'positive' },
      { source: 'CRM', value: 'Booking confirmed', observedAt: '09:10', tone: 'positive' },
      { source: 'Contact permission', value: 'Callback only', observedAt: 'Customer record' },
    ],
    proposedResponse: 'I found your booking for Day 2 at 10:00. A service adviser will call you to arrange a different time. Your current booking remains unchanged until then.',
  },
  {
    id: 'CASE-101',
    customerId: 'CUS-D',
    customerLanguage: 'English',
    channel: 'Web chat',
    receivedAt: 'Yesterday',
    message: 'Has the replacement part arrived?',
    jobId: 'JOB-8',
    vehicle: 'LMN-442 · Parts order',
    classification: 'Repair status',
    confidence: 94,
    status: 'sent',
    deliveredAt: 'Yesterday, 16:42',
    justification: 'The parts record and workshop record agree that the item was received. The response reports the confirmed status without making a completion promise.',
    rules: ['Report confirmed evidence only'],
    evidence: [
      { source: 'Parts system', value: 'Part received', observedAt: 'Yesterday, 15:58', tone: 'positive' },
      { source: 'Workshop', value: 'Installation not started', observedAt: 'Yesterday, 16:04' },
    ],
    proposedResponse: 'Yes, the replacement part arrived today. Installation has not started yet, so the repair completion time is not confirmed.',
  },
]

export const initialConnectors: Connector[] = [
  {
    id: 'whatsapp',
    name: 'WhatsApp Business',
    description: 'Receive customer messages and return approved responses.',
    status: 'not_connected',
  },
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Turn customer emails into reviewable requests.',
    status: 'not_connected',
  },
  {
    id: 'voice',
    name: 'Voice calls',
    description: 'Transcribe calls and prepare responses in real time.',
    status: 'planned',
  },
]
